### ISSUE TITLE
mzPAF doc typos, etc.

### ISSUE THREAD

**Issue by henryhlam** [HUPO-PSI/mzPAF#6]
1. Section 4.4.3. In the table, the formula for calculating x ion mass is wrong. It should be: ∑(AA) + CO - 2H + (H+)z.

2. Section 4.4.4. It was said that if the internal fragment has the same amino acid compositions but different sequence (e.g. EPA vs PEA) one MAY specify both. What if it has the exact same sequence (e.g. m2:3, m3:4, m4:5, m5:6… of the peptide AAAAAAAAAAAAK? Should we specify that we should not repeat it and the one with the lowest n should be used?  

3. Section 4.5. In the table, the row with "CO", last column, "neutral loss" is spelled wrong.

**Comment by edeutsch** [comment]
these are all addressed.
